# Generated by Django 3.2.9 on 2021-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('remarks', models.EmailField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
