# Generated by Django 3.2.9 on 2021-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_rename_email_contact_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phoneno',
            field=models.IntegerField(default=0.0008580008580008579),
            preserve_default=False,
        ),
    ]
